spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Gateway will automatically create routes based on service names
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/
server:
  port: 8088
