package com.videoservice.mapper;
import com.videoservice.dto.MediaRequestDTO;
import com.videoservice.dto.MediaResponseDTO;
import com.videoservice.entity.MediaEntity;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface MediaMapper {

    MediaMapper INSTANCE = Mappers.getMapper(MediaMapper.class);

    // Maps inbound Request DTO to Entity (ID will be ignored/generated by Mongo)
    MediaEntity toEntity(MediaRequestDTO requestDto);

    // Maps Database Entity to outbound Response DTO
    MediaResponseDTO toResponseDto(MediaEntity entity);

    // Updates existing Entity with fields from the Request DTO
    void updateEntityFromDto(MediaRequestDTO requestDto, @MappingTarget MediaEntity entity);
}