server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Now it ONLY looks inside this folder for client configs
          search-locations: classpath:/config-repo/